GET http://localhost:3000/api/Bookings

###
// Getting by ID

### Get a Booking by ID
GET http://localhost:3000/api/Bookings/1
Content-Type: application/json

###

POST http://localhost:3000/api/Bookings
Content-Type: application/json

{
    "user_id":5,
    "vehicle_id": 5,
    "location_id":5,
    "booking_date": "2024-06-24",
    "return_date": "2024-06-24",
    "total_amount": "20000",
    "booking_status": "booked"
}

###
PUT http://localhost:3000/api/Bookings/4
Content-Type: application/json

{

   "booking_status": "not booked"
}
###

DELETE http://localhost:3000/api/Bookings/3