GET http://localhost:3000/api/users

###

###
GET http://localhost:3000/api/users
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsiZnVsbF9uYW1lIjoid2FpcmltdSBlbGlqYWggS2ltYW5pICIsImNvbnRhY3RfcGhvbmUiOiIwNzkxMzM3MTg4IiwiYWRkcmVzcyI6IjEyMyBrZW55YSIsImlkIjo0MH0sInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMTY0Nzg0NX0.fO7GYO8klLnxLnsDdYher4Nmv0SOdV0YNHi3whgpaUg
###
GET http://localhost:3000/api/users/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJLaW0gU29vaHl1biIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDExMDQ0MX0.kxV3QCaBLbhZCsoiUTj5Drj1eEonOO6q2os0byCmNOk
// Getting by ID

### Get a user by ID
GET http://localhost:3000/api/users/9
Content-Type: application/json

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
 
  "username": "Christine",
  "email": "stno@gmail.com",
  "contact_phone": "0745689034",
  "address": "1950",
  "password":"3400",
  "role": "user"
}

###
{
 
 
  "full_name": "Christine Rian ",
  "email": "riyan99@gmail.com",
  "contact_phone": "0799087188",
  "address": "90 kenya",
  "role": "admin",
  "password": "2003"
}
###

POST http://localhost:3000/api/users
Content-Type: application/json

{

  "username": "sine",
  "email": "si6te@gmail.com",
  "contact_phone": "0745689034",
  "address": "1950",
  "password":"3430",
  "role": "user"
}



###
PUT http://localhost:3000/api/users/85
Content-Type: application/json

{

   "address": "70 kutus"
}
###

DELETE http://localhost:3000/api/users/23

