
### List all address with a limit of 10
GET http://localhost:3000/api/register?limit=10
Content-Type: application/json

### Get a address by ID
GET http://localhost:3000/api/register/
Content-Type: application/json

###
GET http://localhost:3000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJLaW0gSml3b24iLCJyb2xlIjoidXNlciIsImV4cCI6MTcyMDA5MTM1M30.9aMOX5wTe0-ekno786u-F0m4tUWxcyCmfUUpqXvU-bU
###
###
GET http://localhost:3000/api/users/7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJLaW0gSml3b24iLCJyb2xlIjoidXNlciIsImV4cCI6MTcyMDA5MTM1M30.9aMOX5wTe0-ekno786u-F0m4tUWxcyCmfUUpqXvU-bU
### 
POST http://localhost:3000/api/register
Content-Type: application/json

{
   "userId":1,
   "username":"Christine Nyambwari",
   "password":"3457",
   "role": "user"

}


### 
POST http://localhost:3000/api/register
Content-Type: application/json

{
   "userId":1,
   "username":"Kim Soohyun",
   "password":"4567",
   "role": "admin"

}
### 
POST http://localhost:3000/api/register
Content-Type: application/json

{
   "userId":1,
   "username":"Kim Jiwon",
   "password":"9067",
   "role": "user"

}
###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username":"Christine Nyambwari",
    "password":"3457"
   
}
###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username":"Kim Soohyun",
    "password":"4567"
   
}
###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username":"Kim Jiwon",
    "password":"9067"
   
}
